package cn.qinxiandiqi.photochecker.feature.home.model

enum class ExifValueType {
    PLAIN_TEXT,
    RATIONAL_APERTURE,
    RATIONAL_FOCAL,
    RATIONAL_EXPOSURE,
    RATIONAL_DISTANCE,
    GPS_COORDINATE,
    GPS_DECIMAL,
    DATETIME,
    ORIENTATION,
    RESOLUTION,
    METERING_MODE,
    FLASH,
    EXPOSURE_PROGRAM,
    WHITE_BALANCE,
    SCENE_CAPTURE,
    COLOR_SPACE,
    EXPOSURE_MODE,
    CONTRAST_SATURATION_SHARPNESS,
    LENS_SPECIFICATION
}
